# Use Node.js official image
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install && npm cache clean --force

ENV PATH=/app/node_modules/.bin:$PATH

WORKDIR /app/dev
COPY tsconfig.json ./

# Copy the rest of the application code
COPY src ./src
# COPY . .

# Expose the port
EXPOSE 3000

COPY src ./src
COPY .env ./

EXPOSE ${PORT}

CMD ["npm", "run", "start:watch"]